name: Check package for vulnerabilities
description: 'Check an npm package for vulnerabilities in dependencies'
inputs:
  working-directory:  # sub-folder containing package
    description: 'Package Sub-Folder'
    required: true
    default: '.'
runs:
  using: "composite"
  steps:
    - name: Check dependencies
      shell: bash
      run: |
        cd ${{ inputs.working-directory }}
        npm audit
