name: Build and test package
description: 'Build and test an npm package'
inputs:
  package-name:  # name of package, used for caching node modules
    description: 'Name of package to build'
    required: true
    default: '.'
runs:
  using: "composite"
  steps:
    - name: Cache node modules
      id: cache-npm
      uses: actions/cache@v3
      env:
        cache-name: cache-node-modules
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: ~/.npm
        key: npm-build-${{ env.cache-name }}-${{ inputs.package-name }}-${{ hashFiles('./package-lock.json') }}

    - name: Install dependencies
      shell: bash
      run: npm install

    - name: Build
      shell: bash
      run: npm run rebuild

    - name: Test
      shell: bash
      run: npm test

    - name: Check coding style
      shell: bash
      run: npm run check-style
