name: Build and test package
description: 'Build and test an npm package'
inputs:
  working-directory:  # sub-folder containing package
    description: 'Package Sub-Folder'
    required: true
    default: '.'
runs:
  using: "composite"
  steps:
    - name: Cache node modules
      id: cache-npm
      uses: actions/cache@v3
      env:
        cache-name: cache-node-modules
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: ~/.npm
        key: npm-build-${{ env.cache-name }}-${{ inputs.working-directory }}-${{ hashFiles('./package-lock.json') }}

    - name: Install dependencies
      shell: bash
      run: |
        pwd
        cd ${{ inputs.working-directory }}
        npm install

    - name: Build
      shell: bash
      run: |
        pwd
        cd ${{ inputs.working-directory }}
        npm run rebuild

    - name: Test
      shell: bash
      run: |
        cd ${{ inputs.working-directory }}
        npm test

    - name: Check coding style
      shell: bash
      run: |
        cd ${{ inputs.working-directory }}
        npm run check-style
