name: Build and test package with npm
description: 'Build and test an npm package'
inputs:
  working-directory:  # sub-folder containing package
    description: 'Package Sub-Folder'
    required: true
    default: '.'
runs:
  using: "composite"
  defaults:
    run:
      working-directory: ${{ inputs.working-directory }}
  steps:
    - name: Cache node modules
      id: cache-npm
      uses: actions/cache@v3
      env:
        cache-name: cache-node-modules
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: ~/.npm
        key: npm-build-${{ env.cache-name }}-${{ inputs.working-directory }}-${{ hashFiles('./package-lock.json') }}

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run rebuild

    - name: Test
      run: npm test

    - name: Check coding style
      run: npm run check-style
