name: Build simple package
description: 'Build (zip up) a simple package'
inputs:
  working-directory:  # sub-folder containing package
    description: 'Package Sub-Folder'
    required: true
    default: '.'
runs:
  using: "composite"
  steps:
    - name: Build
      shell: bash
      run: |
        cd ${{ inputs.working-directory }}
        source build.sh
