name: Build and test example packages with npm
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.5.1'

      - name: Build ProcessFlow
      - uses: .github/workflows/actions/build-package
        with:
          working-directory: 'Examples/ProcessFlow'

