name: 'Check for vulnerabilities in all dependencies'
on:
  workflow_dispatch:
  schedule:
    - cron: '0 5 * * *'
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.15.1'

      - name: Check EChartsBarChart (full)
        uses: ./.github/workflows/actions/check-package
        with:
          working-directory: './Examples/EChartsBarChart'

      - name: Check EChartsRadialTree (full)
        uses: ./.github/workflows/actions/check-package
        with:
          working-directory: './Examples/EChartsRadialTree'

      - name: Check Lollipop (full)
        uses: ./.github/workflows/actions/check-package
        with:
          working-directory: './Examples/Lollipop'

      - name: Check ProcessFlow (full)
        uses: ./.github/workflows/actions/check-package
        with:
          working-directory: './Examples/ProcessFlow'

      - name: Check StretchedChord (full)
        uses: ./.github/workflows/actions/check-package
        with:
          working-directory: './Examples/StretchedChord'

      - name: Check WebpackD3Visualization (full)
        uses: ./.github/workflows/actions/check-package
        with:
          working-directory: './Examples/WebpackD3Visualization'

      - name: Check WebpackReactVisualization (full)
        uses: ./.github/workflows/actions/check-package
        with:
          working-directory: './Examples/WebpackReactVisualization'

      - name: Check WordCloud (full)
        uses: ./.github/workflows/actions/check-package
        with:
          working-directory: './Examples/WordCloud'
